### ISSUE TITLE
Convert `Members` to a list

### ISSUE THREAD

**Issue by gyliu513** [IBM/meta-operator#103]
https://github.com/IBM/meta-operator/blob/master/pkg/apis/operator/v1alpha1/metaoperatorset_types.go#L85

As we need to list all operator status.

FYI @IBM/cs-operator-maintainers

**Comment by gyliu513** [comment]
FYI @IBM/meta-operator-maintainers

**Comment by DanielXLee** [comment]
@gyliu513 The members is a list now, https://github.com/IBM/meta-operator/blob/c26ce2915fe667030dfac9594bdff6bb4b127950/pkg/apis/operator/v1alpha1/metaoperatorset_types.go#L91, this status list includes all ready and unready operator, do you want more detail status?

**Comment by DanielXLee** [comment]
@gyliu513 I have a new improvement for the operand status display, could you help review it, if I miss understanding. `Members` is a list, including all the  operands status of  the set state is `present`, for every operand status including 2 attributes: `name` and `phase`

```go
type MetaOperatorSetStatus struct {
	Conditions []Condition `json:"conditions,omitempty"`
	// Members represnets the current operand status of the set
	// +optional
	Members []MemberStatus `json:"member,omitempty"`
	// Phase is the cluster running phase
	Phase ClusterPhase `json:"phase"`
}
// MemberStatus show if the Operator is ready
type MemberStatus struct {
	// The member names are the same as the subscription
	Name string `json:"name"`
	// The operand phase include None, Creating, Running, Failed
	Phase OperandPhase `json:"phase"`
}
```

**Comment by gyliu513** [comment]
@DanielXLee +1 with your above proposal, the `MemberStatus` should only include one operand status.

**Comment by DanielXLee** [comment]
@gyliu513 
Our meta operator includes 2 parts, create the operator and create operator instance, so I separate the member phase as 2 phases, 
- OperatorPhase: save the phase of creating operator 
- OperandPhase: save the phase of creating operator instance
Do you think we need to divide it into two parts?
```go
type MemberPhase struct {
	OperatorPhase olmv1alpha1.ClusterServiceVersionPhase `json:"operatorPhase,omitempty"`
	OperandPhase  ServicePhase                           `json:"operandPhase,omitempty"`
}
```
