### ISSUE TITLE
Rename some CRDs

### ISSUE THREAD

**Issue by gyliu513** [IBM/meta-operator#3]
Considering we want to make the common service operator as a generic meta operator, so we may need to change the CRD name a bit to make it more generic.

Here are some of my thinking:

- MetaOperator->MetaOperatorCatalog
- CommonServiceConfig->MetaOperatorConfig
- CommonServiceSet->MetaOperatorSet

Please propose your comments here before we go forward.

FYI @chenzhiwei @horis233 @shikhasriva

**Comment by chenzhiwei** [comment]
@horis233 Here is the new CRDs.

**Comment by shikhasriva** [comment]
To make this more consumable by the Clouspaks, can we have the following naming convention 
MetaOperator->MetaOperatorCatalog-> MetaOperatorSvcList
CommonServiceConfig->MetaOperatorConfig->MetaOperatorSvcConfig
CommonServiceSet->MetaOperatorSet-> MetaOperatorSvcSet

**Comment by gyliu513** [comment]
Let's have more discussion for this.

**Comment by DanielXLee** [comment]
Maybe we can remove prefix `Meta`, the following is my propose
```
MetaOperator->MetaOperatorCatalog-> OperatorSource
CommonServiceConfig->MetaOperatorConfig->OperatorConfig
CommonServiceSet->MetaOperatorSet-> OperatorSet
```

**Comment by gyliu513** [comment]
Close this one, we will keep the CRD name unchanged.
