### ISSUE TITLE
build multi-arch image

### ISSUE THREAD

**Issue by chenzhiwei** [IBM/meta-operator#39]
Quay.io is now supporting multiarch image, so it is time to build multiarch image of this operator.

**Comment by gyliu513** [comment]
FYI @morvencao

**Comment by morvencao** [comment]
We're trying to enable prow build on power platform, currently blocked by networking issue of power cluster on IBM Cloud.
After that is resolved, we'll try to enable the multi-arch image build with prow.

**Comment by gyliu513** [comment]
but we still cannot build Z

**Comment by morvencao** [comment]
It is supposed that we cab provision Z cluster as power cluster.

**Comment by chenzhiwei** [comment]
My idea is to build all the images on amd64 machine, so this does not rely on Prow power/Z machine.
