### ISSUE TITLE
Update operator-sdk version to 0.15.1 go version to 1.13.7

### ISSUE THREAD

**Issue by chenzhiwei** [IBM/meta-operator#42]
The latest stable version has more strict checks and will find some potential issue in the code.

### Generate crds

```
operator-sdk generate crds
```

### Generate k8s

```
operator-sdk generate k8s
```

### Generate csv

```
operator-sdk generate csv
```

### Generate openapi

```
which ./bin/openapi-gen > /dev/null || go build -o ./bin/openapi-gen k8s.io/kube-openapi/cmd/openapi-gen

GOPATH=/tmp ./bin/openapi-gen --logtostderr=true -o "" -i ./pkg/apis/operator/v1alpha1 -O zz_generated.openapi -p ./pkg/apis/operator/v1alpha1/ -h ./hack/boilerplate.go.txt -r "-"
```

##

**Comment by gyliu513** [comment]
Update operator-sdk version to 0.15.1 go version to 1.13.7

**Comment by gyliu513** [comment]
@chenzhiwei can you clarify what is `some potential issue`? If there are issues, we may want all operators upgrade to use this sdk.

**Comment by chenzhiwei** [comment]
@gyliu513 You can check the PR about the new operator validation and generated code: https://github.com/IBM/meta-operator/pull/43
