### ISSUE TITLE
Update metaOperatorCatalog

### ISSUE THREAD

**Issue by horis233** [IBM/meta-operator#58]
@DanielXLee 
Currently, we only update the subscription when the channel changes.
https://github.com/IBM/meta-operator/blob/master/pkg/controller/metaoperatorset/reconcile_metaoperatorcatalog.go#L57

Do we need to reconcile metaOperatorCatalog when `Package` `CatalogSource` and `CatalogSourceNamespace` change?

if a user makes a typo on the value `CatalogSource` in the metaOperatorConfig, he can't correct it by update metaOperatorCatalog. He has to manually delete the hanging subscription before he corrects the metaOperatorCatalog.

**Comment by DanielXLee** [comment]
I think we can watch the change of CatalogSource and CatalogSourceNamespace, but don't need to watch the  Package change. Package change means it's a new operator.
